using System.Text.Json.Serialization;

namespace CaseGen.Functions.Models.CaseV2;

/// <summary>
/// Structured document model used to render rich PDFs without inventing a renderer
/// per evidence type. The LLM emits an <see cref="EvidenceDocument"/> for any asset
/// of type <c>pdf</c>, <c>document</c> or <c>digital</c>; the renderer maps each
/// section <c>kind</c> to a QuestPDF block (paragraph, table, key/value list,
/// transcript, code block, attribution).
/// </summary>
public class EvidenceDocument
{
    /// <summary>Short PascalCase tag for the layout. Examples: PoliceReport,
    /// CallLog, PosExport, PhoneDump, SensorLog, BrowserHistory, BankStatement,
    /// FileListing, ForensicReport, InterviewTranscript, GeneralReport.</summary>
    [JsonPropertyName("layout")] public string Layout { get; set; } = "GeneralReport";

    /// <summary>BCP-47 language tag (en-US, pt-BR, es-ES, fr-FR). Drives the
    /// localized chrome strings the renderer writes around the LLM body.
    /// Propagated from <c>CaseGenerationRequest.Language</c> when emitting
    /// the asset; defaults to en-US so older artifacts stay valid.</summary>
    [JsonPropertyName("language")] public string Language { get; set; } = "en-US";

    [JsonPropertyName("title")] public string Title { get; set; } = string.Empty;
    [JsonPropertyName("subtitle")] public string? Subtitle { get; set; }
    [JsonPropertyName("classification")] public string Classification { get; set; } = "CONFIDENTIAL · INTERNAL USE ONLY";

    /// <summary>Free key/value pairs shown in the header block (Case ref, exhibit ref,
    /// generated by, generated at, station, etc.).</summary>
    [JsonPropertyName("header")] public List<EvidenceKeyValue> Header { get; set; } = new();

    [JsonPropertyName("sections")] public List<EvidenceSection> Sections { get; set; } = new();

    /// <summary>Optional signature block (officer name + badge + date).</summary>
    [JsonPropertyName("signature")] public EvidenceSignature? Signature { get; set; }
}

public class EvidenceSection
{
    [JsonPropertyName("kind")] public string Kind { get; set; } = "narrative"; // narrative | table | keyValue | transcript | code | callout

    [JsonPropertyName("heading")] public string? Heading { get; set; }

    /// <summary>Markdown / prose body. Used when kind == narrative or callout.</summary>
    [JsonPropertyName("text")] public string? Text { get; set; }

    /// <summary>Tabular content. Used when kind == table.</summary>
    [JsonPropertyName("table")] public EvidenceTable? Table { get; set; }

    /// <summary>Used when kind == keyValue.</summary>
    [JsonPropertyName("items")] public List<EvidenceKeyValue>? Items { get; set; }

    /// <summary>Used when kind == transcript.</summary>
    [JsonPropertyName("transcript")] public List<EvidenceTranscriptEntry>? Transcript { get; set; }

    /// <summary>Used when kind == code (logs, machine-emitted data).</summary>
    [JsonPropertyName("code")] public EvidenceCode? Code { get; set; }
}

public class EvidenceTable
{
    [JsonPropertyName("columns")] public List<string> Columns { get; set; } = new();
    [JsonPropertyName("rows")] public List<List<string>> Rows { get; set; } = new();
    /// <summary>Optional caption / footnote below the table.</summary>
    [JsonPropertyName("footnote")] public string? Footnote { get; set; }
}

public class EvidenceKeyValue
{
    [JsonPropertyName("label")] public string Label { get; set; } = string.Empty;
    [JsonPropertyName("value")] public string Value { get; set; } = string.Empty;
}

public class EvidenceTranscriptEntry
{
    [JsonPropertyName("timestamp")] public string? Timestamp { get; set; }
    [JsonPropertyName("speaker")] public string? Speaker { get; set; }
    [JsonPropertyName("text")] public string Text { get; set; } = string.Empty;
}

public class EvidenceCode
{
    [JsonPropertyName("language")] public string? Language { get; set; } // optional, for hint only
    [JsonPropertyName("content")] public string Content { get; set; } = string.Empty;
}

public class EvidenceSignature
{
    [JsonPropertyName("name")] public string Name { get; set; } = string.Empty;
    [JsonPropertyName("badge")] public string? Badge { get; set; }
    [JsonPropertyName("title")] public string? Title { get; set; }
    [JsonPropertyName("signedAt")] public string? SignedAt { get; set; }
}
