using System.Text.Json;
using CaseGen.Functions.Models.CaseV2;
using Microsoft.Extensions.Logging;

namespace CaseGen.Functions.Services.CaseV2.Tasks;

/// <summary>
/// Stage 12 — Refine. When schema validation still has errors after the deterministic
/// auto-fixer ran, OR when the red-team agent verdict was <c>reject</c> with at least one
/// high-severity finding, this task asks the LLM to emit a corrected JSON document.
///
/// Strategy: send the full case.json (which is small — ~30-40 KB), the error list, and
/// any high-severity findings. The model must return JSON that satisfies the v2 schema
/// AND preserves the case content as much as possible. We only call this once per
/// generation — repeated refines are expensive and rarely converge.
/// </summary>
public class RefineCaseTask
{
    private readonly ILLMProvider _llm;
    private readonly ILogger _logger;

    public RefineCaseTask(ILLMProvider llm, ILogger logger)
    {
        _llm = llm;
        _logger = logger;
    }

    public class Result
    {
        public string? RefinedJson { get; set; }
        public bool Succeeded => !string.IsNullOrEmpty(RefinedJson);
        public string? Error { get; set; }
    }

    public async Task<Result> RunAsync(
        string currentJson,
        IReadOnlyList<string> validationErrors,
        IReadOnlyList<RedTeamTask.Finding> findings,
        string schemaJson,
        CancellationToken ct,
        string? difficulty = null)
    {
        var errorBlock = validationErrors.Count == 0
            ? "(no schema errors)"
            : string.Join("\n", validationErrors.Select(e => "- " + e));

        var highFindings = findings.Where(f =>
            string.Equals(f.Severity, "high", StringComparison.OrdinalIgnoreCase)).ToList();
        var mediumFindings = findings.Where(f =>
            string.Equals(f.Severity, "medium", StringComparison.OrdinalIgnoreCase)).ToList();

        var highBlock = highFindings.Count == 0
            ? "(no high-severity red-team findings)"
            : string.Join("\n", highFindings.Select(f =>
                $"- area={f.Area} severity={f.Severity} issue={f.Issue}" +
                (string.IsNullOrEmpty(f.Suggestion) ? "" : $" suggestion={f.Suggestion}") +
                (string.IsNullOrEmpty(f.OwnerStage) ? "" : $" ownerStage={f.OwnerStage}") +
                (string.IsNullOrEmpty(f.RepairAction) ? "" : $" repairAction={f.RepairAction}") +
                (f.AffectedPaths.Count == 0 ? "" : $" affectedPaths={string.Join(",", f.AffectedPaths)}")));

        var mediumBlock = mediumFindings.Count == 0
            ? "(no medium-severity red-team findings)"
            : string.Join("\n", mediumFindings.Select(f =>
                $"- area={f.Area} severity={f.Severity} issue={f.Issue}" +
                (string.IsNullOrEmpty(f.Suggestion) ? "" : $" suggestion={f.Suggestion}") +
                (string.IsNullOrEmpty(f.OwnerStage) ? "" : $" ownerStage={f.OwnerStage}") +
                (string.IsNullOrEmpty(f.RepairAction) ? "" : $" repairAction={f.RepairAction}") +
                (f.AffectedPaths.Count == 0 ? "" : $" affectedPaths={string.Join(",", f.AffectedPaths)}")));

        var areaGuidance = BuildAreaGuidance(findings);
        var isRookie = string.Equals(difficulty, "Rookie", StringComparison.OrdinalIgnoreCase);

        var system = @"You are the **refine agent** for an interactive detective case. You receive a case.json document that failed validation or red-team review, plus the list of problems. Your job is to emit a corrected case.json that:

1. Satisfies every JSON-Schema constraint listed in the supplied schema (especially id-pattern constraints like `^asset\.[a-z0-9_]+$`, `^tevt\.[a-z0-9_]+$`, etc.).
2. Addresses every high-severity red-team finding listed.
3. Also addresses medium-severity findings whenever doing so does not require restructuring the case (e.g. sharpening a motive, tightening an alibi, clarifying a forensic conclusion).
4. Preserves the rest of the case as faithfully as possible — DO NOT rewrite plot, suspects, timeline, motive, evidence, or solution unless explicitly required to fix a flagged issue. Keep IDs stable when fixing referential issues; if an ID must change, also update every reference to it.
5. Emit ONLY the corrected JSON document — no commentary, no markdown fences. The top-level must be an object matching the v2 case schema.

Be surgical. If the only complaint is malformed IDs, just fix the IDs (and their references). If a finding says ""smoking gun too weak"", you may add a sentence to the relevant ConclusionText or sharpen a forensic outcome, but don't restructure the case.";
        system += @"
Never add new assets, emails, suspects, rules, or temporal events during refinement. Their rendered content is owned by upstream agents. Repair the existing JSON surfaces only; findings that require new evidence must be regenerated by their owner stage rather than fabricated here.";

        if (!string.IsNullOrEmpty(areaGuidance))
        {
            system += "\n\n=== AREA-SPECIFIC PLAYBOOKS ===\nThe red-team flagged issues in the following areas. Apply the matching playbook precisely — these are the highest-leverage edits for getting the case promoted to `ok`.\n" + areaGuidance;
        }

        if (isRookie)
        {
            system += @"

=== ROOKIE CONTEXT ===
This case is a **Rookie** training case. Be decisive while keeping the dossier compact:
- Remove every forensic outcome, forensic result asset/email, forensic reveal rule, and requiredAnalysisId. Keep `forensicsDefaults.analysisTypes` as an empty array.
- Move any decisive fact currently present only in a forensic result into an existing initial evidence document, without revealing the culprit directly.
- If a Timeline event contradicts the briefing or another event, **pick the version implied by the solution and rewrite the conflicting prose**. Do not leave both versions in place.
- If the public timeline or suspect profile reveals the culprit or hidden method, replace it with an observable discovery rather than private truth.
- If a SmokingGun finding says the evidence is ambiguous, **add concrete corroborating detail to the evidence asset itself** (a timestamp, a fresh-print marker, a witness reference) AND mirror that detail in the corresponding ConclusionText / solution reasoning.
- If a Question presupposes a fact the dossier does not show, **either rewrite the question to ask only what the evidence supports, or add the missing fact to the supporting asset**.
- Do not add new assets or emails to verify every decoy. If a decoy lacks player-visible support, set `alibiVerified=false` or consolidate the fact into an existing document.
- Do not invent new suspects, new locations, or new red herrings. Modify existing prose only.";
        }

        var user = $@"=== CURRENT case.json ===
{currentJson}

=== VALIDATION ERRORS ===
{errorBlock}

=== HIGH-SEVERITY RED-TEAM FINDINGS ===
{highBlock}

=== MEDIUM-SEVERITY RED-TEAM FINDINGS ===
{mediumBlock}

Emit the corrected case.json as a single JSON object.";

        try
        {
            var raw = await _llm.GenerateStructuredResponseAsync(system, user, schemaJson, ct);
            // Trust the structured-response API to return JSON; do a parse round-trip as
            // a sanity check before handing it back up the pipeline.
            using var doc = JsonDocument.Parse(raw.Content);
            _logger.LogInformation("RefineCaseTask emitted {Bytes} bytes of refined JSON", raw.Content.Length);
            return new Result { RefinedJson = raw.Content };
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "RefineCaseTask failed");
            return new Result { Error = ex.Message };
        }
    }

    /// <summary>
    /// Inspect the findings to detect which high-leverage areas were flagged, then emit a
    /// concrete playbook for each. This is the single biggest lever for clearing medium
    /// findings on a Rookie case in one refine pass — generic "be surgical" guidance is
    /// not enough when the LLM has to choose between rephrasing prose vs. fixing logic.
    /// </summary>
    private static string BuildAreaGuidance(IReadOnlyList<RedTeamTask.Finding> findings)
    {
        var actionable = findings
            .Where(f => !string.Equals(f.Severity, "low", StringComparison.OrdinalIgnoreCase))
            .Select(f => NormalizeArea(f.Area))
            .Where(a => !string.IsNullOrEmpty(a))
            .ToHashSet();
        if (actionable.Count == 0) return string.Empty;

        var sb = new System.Text.StringBuilder();

        if (actionable.Contains("timeline"))
        {
            sb.AppendLine(@"
[Timeline]
- Two events with conflicting timestamps or contradictory descriptions MUST be reconciled. Pick the version implied by the solution (or by the briefing if the solution is silent) and rewrite OR delete the conflicting event.
- Every timeline event with a specific time should be anchored by something visible to the player — an asset, a witness statement, or a forensic outcome. If no anchor exists, either add a brief source attribution in the event description or remove the precise time.
- Verify `openedAt`, the briefing prose, and every `timelineEvents[].at` align on date AND hour. A discrepancy here is the #1 cause of `needs_review`.
- When you change an event time, also update any narrative text (briefing, asset descriptions, ConclusionText) that referenced the old time.");
        }

        if (actionable.Contains("smokinggun"))
        {
            sb.AppendLine(@"
[SmokingGun]
- The conclusive evidence must be hard to explain away. If a finding says the smoking gun is ambiguous, add ONE of these concrete enhancements to the underlying evidence asset (and mirror it in `solution.conclusionText` / forensic outcome text):
  (a) **Recency marker**: ""trace fraîche"" / ""prelevamento recente"" / fresh deposit / timestamp from sensor / CCTV frame at HH:MM.
  (b) **Exclusive signature**: a unique characteristic that only the culprit could have left (an unusual substance, a personal item, a biometric tied to a verified profile).
  (c) **Independent corroboration**: a second asset (witness, sensor log, transaction record) that places the same person/object at the same time.
- Do NOT add new suspects, new locations, or new high-level plot beats. The fix is always at the level of evidence detail, not story structure.");
        }

        if (actionable.Contains("questions"))
        {
            sb.AppendLine(@"
[Questions]
- Every question's correct answer MUST be directly derivable from the assets the player can read. If a question presupposes a fact (""quel canal a permis..."", ""qual foi o motivo..."") the dossier MUST contain an asset that states that fact in plain prose.
- Two valid fixes:
  (1) **Add the missing fact** to the supporting asset description / ConclusionText (preferred — preserves the question).
  (2) **Rephrase the question** so the presupposition becomes part of the question (""sachant que la porte arrière était compatible, qui...""), or downgrade it to ask only what the evidence supports.
- Never leave a question whose correct answer requires the player to guess between equally-supported options.");
        }

        if (actionable.Contains("requiredevidence"))
        {
            sb.AppendLine(@"
[RequiredEvidence]
- Every id in `solution.requiredEvidenceIds` MUST resolve to an asset the player can actually obtain. Two valid shapes:
  (1) The id matches an entry in `assets[]` whose visibility makes it readable in the player's flow.
  (2) The id matches an asset produced by a forensic outcome (and that forensic input/outcome chain is reachable).
- If a referenced id does not exist, either add the missing asset (preferred) or replace the id with the closest existing asset id and update all other references consistently.
- Do not silently drop an id from `requiredEvidenceIds` unless the solution genuinely no longer depends on it.");
        }

        if (actionable.Contains("forensics"))
        {
            sb.AppendLine(@"
[Forensics]
- Every forensic outcome must (a) name the specific input asset it consumed, (b) describe a concrete observation (not an authority claim like ""présence détectée""), and (c) produce an output asset id that exists in `assets[]` or is added by this refine.
- Replace vague phrases (""compatible"", ""présence à proximité"", ""possibly linked"") with concrete observations (cell-ID + sector, timestamp, distinguishing mark).");
        }

        if (actionable.Contains("decoys"))
        {
            sb.AppendLine(@"
[Decoys]
- Each decoy suspect needs an alibi the player can VERIFY from a visible asset (CCTV log, transaction record, GPS trace), not just a narrative claim.
- If an alibi is described as ""confirmed by video/CB/GPS"" but no such asset is in `assets[]`, add the minimal supporting asset OR weaken the alibi prose so it doesn't promise verification that doesn't exist.");
        }

        return sb.ToString();
    }

    private static string NormalizeArea(string? area)
    {
        if (string.IsNullOrWhiteSpace(area)) return string.Empty;
        // Red-team uses both "Smoking-gun"/"SmokingGun" and "Required-evidence"/"RequiredEvidence".
        return new string(area.ToLowerInvariant().Where(char.IsLetterOrDigit).ToArray());
    }
}
