# Case Generator Infrastructure Configuration
# This file defines the configuration for deploying ONLY the Case Generator infrastructure

apiVersion: v1
kind: Config
metadata:
  name: case-generator-infrastructure
  description: Infrastructure configuration for CaseZero Case Generator AI
  version: "1.0.0"
  tags:
    - casezero
    - case-generator
    - ai
    - infrastructure

# Component Information
component:
  name: "Case Generator"
  description: "AI-powered case generation system for CaseZero platform"
  type: "infrastructure"
  owner: "CaseZero Team"
  
# Infrastructure Configuration
infrastructure:
  # Azure Resource Configuration
  azure:
    # Resource Groups (separate from main application)
    resourceGroups:
      development: "casezero-casegen-dev-rg"
      production: "casezero-casegen-prod-rg"
    
    # Location for all resources
    location: "East US 2"
    
    # Naming Convention
    naming:
      prefix: "casezero"
      component: "casegen"
      pattern: "{prefix}-{component}-{resource}-{environment}"
    
    # Resource Configuration by Environment
    environments:
      development:
        functionApp:
          sku: "Y1"  # Consumption plan
          tier: "Dynamic"
          maxWorkers: 1
        storage:
          sku: "Standard_LRS"  # Locally redundant
          tier: "Standard"
        keyVault:
          sku: "standard"
          retentionDays: 7
        monitoring:
          retentionDays: 30
          samplingPercentage: 50
      
      production:
        functionApp:
          sku: "EP1"  # Premium plan
          tier: "ElasticPremium"
          maxWorkers: 10
        storage:
          sku: "Standard_GRS"  # Geo-redundant
          tier: "Standard"
        keyVault:
          sku: "standard"
          retentionDays: 90
        monitoring:
          retentionDays: 90
          samplingPercentage: 100

# Required Azure Resources
resources:
  # Function App for Case Generator workloads
  - type: "Microsoft.Web/sites"
    name: "Function App"
    description: "Azure Function App for running Case Generator AI workflows"
    purpose: "Hosts the AI case generation pipeline with 10-step workflow"
    dependencies:
      - "Function App Service Plan"
      - "Storage Account"
      - "Application Insights"
    
  # Dedicated Function App Service Plan
  - type: "Microsoft.Web/serverfarms"
    name: "Function App Service Plan"
    description: "Dedicated service plan for Case Generator functions"
    purpose: "Isolated compute resources for AI workloads"
    
  # Storage Account for cases and bundles
  - type: "Microsoft.Storage/storageAccounts"
    name: "Storage Account"
    description: "Storage for generated cases, bundles, and temporary files"
    purpose: "Persistent storage for case artifacts and pipeline data"
    containers:
      - name: "cases"
        description: "Individual case files and metadata"
      - name: "bundles"
        description: "Packaged case bundles ready for distribution"
        
  # Key Vault for secrets management
  - type: "Microsoft.KeyVault/vaults"
    name: "Key Vault"
    description: "Secure storage for API keys and sensitive configuration"
    purpose: "Centralized secrets management for AI services"
    
  # Application Insights for monitoring
  - type: "Microsoft.Insights/components"
    name: "Application Insights"
    description: "Application performance monitoring and logging"
    purpose: "Monitor case generation performance and troubleshoot issues"
    
  # Log Analytics Workspace
  - type: "Microsoft.OperationalInsights/workspaces"
    name: "Log Analytics Workspace"
    description: "Centralized logging and analytics platform"
    purpose: "Store and analyze application logs and metrics"

# Security Configuration
security:
  # Identity and Access Management
  identity:
    type: "SystemAssigned"
    description: "Managed identity for secure resource access"
    
  # Role-Based Access Control
  rbac:
    - role: "Key Vault Secrets User"
      principal: "Function App"
      scope: "Key Vault"
      
    - role: "Storage Blob Data Contributor"
      principal: "Function App"
      scope: "Storage Account"
      
  # Network Security
  network:
    httpsOnly: true
    minTlsVersion: "1.2"
    publicAccess: "Enabled"  # Can be restricted in production
    
# Deployment Configuration
deployment:
  # Bicep Template
  template: "infrastructure/bicep/case-generator.bicep"
  
  # Parameter Files
  parameters:
    development: "infrastructure/bicep/case-generator-parameters.dev.json"
    production: "infrastructure/bicep/case-generator-parameters.prod.json"
    
  # GitHub Actions Workflow
  workflow: ".github/workflows/case-generator-infrastructure.yml"
  
  # Deployment Strategy
  strategy:
    type: "blue-green"
    validation: true
    whatIf: true
    rollback: "automatic"

# Monitoring and Observability
monitoring:
  # Key Metrics
  metrics:
    - name: "Function Execution Count"
      description: "Number of case generation requests processed"
      threshold: "1000/hour"
      
    - name: "Function Duration"
      description: "Average case generation time"
      threshold: "30 minutes"
      
    - name: "Error Rate"
      description: "Percentage of failed case generations"
      threshold: "5%"
      
    - name: "Storage Usage"
      description: "Storage consumption for cases and bundles"
      threshold: "100GB"
      
  # Alerts
  alerts:
    - name: "High Error Rate"
      condition: "ErrorRate > 10%"
      action: "email + teams"
      
    - name: "Function Timeout"
      condition: "Duration > 45 minutes"
      action: "teams"
      
    - name: "Storage Full"
      condition: "StorageUsage > 80%"
      action: "email + teams"

# Case Generation Pipeline Configuration
pipeline:
  # 10-Step AI Pipeline
  steps:
    1:
      name: "Plan"
      description: "Create initial case structure and framework"
      timeout: "5 minutes"
      
    2:
      name: "Expand"
      description: "Generate detailed suspects, evidence, and timeline"
      timeout: "10 minutes"
      
    3:
      name: "Design"
      description: "Design investigation flow and game mechanics"
      timeout: "5 minutes"
      
    4:
      name: "GenDocs"
      description: "Generate investigation documents"
      timeout: "15 minutes"
      
    5:
      name: "GenMedia"
      description: "Create media assets and image prompts"
      timeout: "10 minutes"
      
    6:
      name: "Normalize"
      description: "Standardize content and format"
      timeout: "5 minutes"
      
    7:
      name: "Index"
      description: "Create searchable metadata"
      timeout: "3 minutes"
      
    8:
      name: "RuleValidate"
      description: "Quality assurance checks"
      timeout: "5 minutes"
      
    9:
      name: "RedTeam"
      description: "Security and content validation"
      timeout: "5 minutes"
      
    10:
      name: "Package"
      description: "Final assembly and storage"
      timeout: "5 minutes"

# Cost Optimization
cost:
  # Development Environment
  development:
    estimatedMonthlyCost: "$50-100"
    optimizations:
      - "Consumption plan for Function App"
      - "LRS storage for non-critical data"
      - "Reduced log retention"
      
  # Production Environment
  production:
    estimatedMonthlyCost: "$200-500"
    optimizations:
      - "Premium plan with auto-scaling"
      - "GRS storage for data protection"
      - "Extended monitoring retention"

# Integration Points
integration:
  # Main CaseZero Application
  mainApp:
    endpoint: "https://casezero-web-{env}.azurewebsites.net"
    authentication: "Azure AD"
    
  # AI Services
  aiServices:
    - name: "Azure OpenAI"
      purpose: "Text generation and processing"
      configuration: "Key Vault secrets"
      
    - name: "Azure Computer Vision"
      purpose: "Image analysis and generation"
      configuration: "Key Vault secrets"

# Documentation
documentation:
  setup: "docs/CASE_GENERATOR_SETUP.md"
  architecture: "docs/CASE_GENERATOR_ARCHITECTURE.md"
  deployment: "docs/cicd/case-generator-deployment.md"
  troubleshooting: "docs/CASE_GENERATOR_TROUBLESHOOTING.md"